openapi: 3.0.3
info:
  title: A-Tasks
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: 'Attempt to authenticate a new session.'
      operationId: attemptToAuthenticateANewSession
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: pacocha.lelah@example.org
                password:
                  type: string
                  description: ''
                  example: Fd4Rs3CZ
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'Destroy an authenticated session.'
      operationId: destroyAnAuthenticatedSession
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/forgot-password:
    post:
      summary: 'Send a reset link to the given user.'
      operationId: sendAResetLinkToTheGivenUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/reset-password:
    post:
      summary: "Reset the user's password."
      operationId: resetTheUsersPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: illum
                password:
                  type: string
                  description: ''
                  example: et
              required:
                - token
                - password
      security: []
  /api/user/register:
    post:
      summary: 'Create a new registered user.'
      operationId: createANewRegisteredUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: otlesjkczancgxfqu
                apelido:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: btpnviwrrm
                data_nascimento:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-31T06:49:30'
                endereco:
                  type: string
                  description: 'Must not be greater than 512 characters.'
                  example: zhrcjkdjngjzpusuevp
                telefone:
                  type: string
                  description: 'Must be at least 9 characters.'
                  example: jlpozbrpcekeysmsvtkjmoeuljrriqhcsahyopplbrecmoapsvqbiaifshnadhzafj
                role_id:
                  type: number
                  description: ''
                  example: 957573.0128012
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: arnaldo37@example.com
                password:
                  type: string
                  description: ''
                  example: 'xH!?0s/q1.f7;jy'
              required:
                - nome
                - apelido
                - data_nascimento
                - endereco
                - telefone
                - role_id
                - email
                - password
      security: []
  '/api/email/verify/{id}/{hash}':
    get:
      summary: "Mark the authenticated user's email address as verified."
      operationId: markTheAuthenticatedUsersEmailAddressAsVerified
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the verify.'
        example: nam
        required: true
        schema:
          type: string
      -
        in: path
        name: hash
        description: ''
        example: rerum
        required: true
        schema:
          type: string
  /api/email/verification-notification:
    post:
      summary: 'Send a new email verification notification.'
      operationId: sendANewEmailVerificationNotification
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/password:
    put:
      summary: "Update the user's password."
      operationId: updateTheUsersPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/confirmed-password-status:
    get:
      summary: 'Get the password confirmation status.'
      operationId: getThePasswordConfirmationStatus
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/user/confirm-password:
    post:
      summary: "Confirm the user's password."
      operationId: confirmTheUsersPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/admin:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  current_page: 1
                  data:
                    -
                      id: 1
                      user_id: 1
                      nome: 'Elton Vagner'
                      apelido: Bata
                      data_nascimento: '2002-12-14'
                      endereco: 'Maputo, Cidade da Matola, Intaka'
                      email: elton@gmail.com
                      telefone: '879030182'
                      created_at: '2023-07-29T15:47:17.000000Z'
                      updated_at: '2023-07-29T15:47:17.000000Z'
                    -
                      id: 3
                      user_id: 12
                      nome: Ivan
                      apelido: Bata
                      data_nascimento: '2000-01-08'
                      endereco: Intaka
                      email: teste@gmail.com
                      telefone: '888888888888'
                      created_at: '2023-07-30T12:34:28.000000Z'
                      updated_at: '2023-07-30T17:13:40.000000Z'
                    -
                      id: 8
                      user_id: 17
                      nome: Jafton
                      apelido: Bata
                      data_nascimento: '2000-01-08'
                      endereco: Matola
                      email: teste@yahoo.com
                      telefone: '888888899'
                      created_at: '2023-07-31T06:12:52.000000Z'
                      updated_at: '2023-07-31T06:12:52.000000Z'
                  first_page_url: 'http://localhost/api/v1/admin?page=1'
                  from: 1
                  last_page: 1
                  last_page_url: 'http://localhost/api/v1/admin?page=1'
                  links:
                    -
                      url: null
                      label: '&laquo; Previous'
                      active: false
                    -
                      url: 'http://localhost/api/v1/admin?page=1'
                      label: '1'
                      active: true
                    -
                      url: null
                      label: 'Next &raquo;'
                      active: false
                  next_page_url: null
                  path: 'http://localhost/api/v1/admin'
                  per_page: 5
                  prev_page_url: null
                  to: 3
                  total: 3
                properties:
                  current_page:
                    type: integer
                    example: 1
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        user_id: 1
                        nome: 'Elton Vagner'
                        apelido: Bata
                        data_nascimento: '2002-12-14'
                        endereco: 'Maputo, Cidade da Matola, Intaka'
                        email: elton@gmail.com
                        telefone: '879030182'
                        created_at: '2023-07-29T15:47:17.000000Z'
                        updated_at: '2023-07-29T15:47:17.000000Z'
                      -
                        id: 3
                        user_id: 12
                        nome: Ivan
                        apelido: Bata
                        data_nascimento: '2000-01-08'
                        endereco: Intaka
                        email: teste@gmail.com
                        telefone: '888888888888'
                        created_at: '2023-07-30T12:34:28.000000Z'
                        updated_at: '2023-07-30T17:13:40.000000Z'
                      -
                        id: 8
                        user_id: 17
                        nome: Jafton
                        apelido: Bata
                        data_nascimento: '2000-01-08'
                        endereco: Matola
                        email: teste@yahoo.com
                        telefone: '888888899'
                        created_at: '2023-07-31T06:12:52.000000Z'
                        updated_at: '2023-07-31T06:12:52.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        user_id:
                          type: integer
                          example: 1
                        nome:
                          type: string
                          example: 'Elton Vagner'
                        apelido:
                          type: string
                          example: Bata
                        data_nascimento:
                          type: string
                          example: '2002-12-14'
                        endereco:
                          type: string
                          example: 'Maputo, Cidade da Matola, Intaka'
                        email:
                          type: string
                          example: elton@gmail.com
                        telefone:
                          type: string
                          example: '879030182'
                        created_at:
                          type: string
                          example: '2023-07-29T15:47:17.000000Z'
                        updated_at:
                          type: string
                          example: '2023-07-29T15:47:17.000000Z'
                  first_page_url:
                    type: string
                    example: 'http://localhost/api/v1/admin?page=1'
                  from:
                    type: integer
                    example: 1
                  last_page:
                    type: integer
                    example: 1
                  last_page_url:
                    type: string
                    example: 'http://localhost/api/v1/admin?page=1'
                  links:
                    type: array
                    example:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/v1/admin?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          example: null
                        label:
                          type: string
                          example: '&laquo; Previous'
                        active:
                          type: boolean
                          example: false
                  next_page_url:
                    type: string
                    example: null
                  path:
                    type: string
                    example: 'http://localhost/api/v1/admin'
                  per_page:
                    type: integer
                    example: 5
                  prev_page_url:
                    type: string
                    example: null
                  to:
                    type: integer
                    example: 3
                  total:
                    type: integer
                    example: 3
      tags:
        - Endpoints
      security: []
  '/api/v1/admin/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the admin.'
        example: 1
        required: true
        schema:
          type: integer
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
